[tool.black]
line-length = 120
target-version = ['py310']
fast = true

[tool.isort]
profile = "black"
extend_skip_glob = ["tests/**", "*/__init__.py"]
skip_gitignore = true
line_length = 120
multi_line_output = 9
force_single_line = true
float_to_top = true

[tool.pylint.messages_control]
disable = "C0103,C0415,W0613,C0114"